frontend/README.md, frontend/app/layout.js, frontend/app/page.js, frontend/app/play/_components/BaseMap.js, frontend/app/play/page.js, frontend/next.config.mjs, frontend/package-lock.json, frontend/package.json, frontend/tailwind.config.js
I added a basic homepage with some placeholder video for the background. Eventually, we'll have some footage of the University there instead. I also added a little guide on Next.js App Router to the /frontend/README for those of us who are familiar with older versions of Next.js but not App Router.
=> #2: Add basic Homepage

frontend/app/testdb/page.js, frontend/package.json, frontend/utils/db.js
Just setup the DB to run in production as well as in dev.
=> #9: Make DB work in Production as well

frontend/prisma/migrations/20241001010525_add_game_state/migration.sql, frontend/prisma/schema.prisma
=> changes to DB

frontend/app/imagetest/_components/ResizeableMap.js, frontend/app/imagetest/page.js, frontend/next.config.mjs, frontend/package.json
Added a mockup at the route /imagetest to show how full screen images and opening the map could look.
=> #14: Add mockup for full screen images

frontend/app/_utils/ut.js, frontend/app/imageupload/_components/UploadForm.js, frontend/app/imageupload/page.js, frontend/package-lock.json, frontend/package.json, frontend/tailwind.config.js
Added a basic, password protected image upload page for us to use.
=> #17: Add image upload page

frontend/app/page.js
Disabled caching when loading contributor info and made some visual tweaks.
=> #19: Contributor Section Improvements

.vscode/extensions.json, .vscode/settings.json
Added default formatter and some basic settings to the project VS Code configuration so that we're all on the same page in terms of auto-formatting.
=> #21: Add defaults for VS Code

frontend/app/play/page.js
Fix logic for loading images to make sure we don't randomly pick the same one twice.
=> #22: Fix Location Showing Twice

frontend/app/imageupload/error.js, frontend/app/imageupload/page.js, frontend/package-lock.json, frontend/package.json, package-lock.json
- Display custom error messages
- New error page
- Convert HEIC to PNG automatically
=> HEIC compatibility / Error Handling

.vscode/settings.json, frontend/app/dev/page.js, frontend/app/page.js, frontend/app/photos/[id]/_components/BackButton.js, frontend/app/photos/[id]/page.js, frontend/app/photos/_components/CustomMarker.js, frontend/app/photos/_components/Map.js, frontend/app/photos/_components/MapMarkerWrapper.js, frontend/app/photos/page.js
Added a map of all our photos. (We can use this later to approve new photos, edit, delete, etc)
https://github.com/user-attachments/assets/04906eea-cf71-42d0-b542-8a6c0e01f1be
Also added a page that links to all of our dev tools so that they are easier to find.
=> #28: Add Dev Tools Page and Map of all Photos

frontend/app/play/_components/DebugMenu.js, frontend/app/play/_components/EndDialog.js, frontend/app/play/_components/ResultsDialog.js, frontend/app/play/_utils/gameStateUtils.js, frontend/app/play/page.js
Got the end screen to show up at the right time
=> Fixed End Screen

frontend/prisma/migrations/20241023004504_add_campus_enum/migration.sql, frontend/prisma/schema.prisma
Add an Enum for what campus the photo was taken on (WestBank, EastBankCore, EastBankOuter, Dinkytown, and StPaul).
=> #41: Database update: add CampusEnum

frontend/prisma/migrations/20241023004504_add_campus_enum/migration.sql, frontend/prisma/schema.prisma
Same update as #42, merging to main as well to ensure everybody has the updated db schema.
=> #43: Datbase update: merge to main as well

frontend/app/play/_components/MapWrapper.js
Most issues for enter keybinding have been fixed now. (infinite games can no longer be played, enter cannot be used to submit a guess before clicking a guess). Whats left is to make the enter key take the user through the EndResultsScreen and have enter be "play again" and Esc be "home"
=> Further Fixing of Enter Kebinding

frontend/app/imageupload/_components/UploadForm.js, frontend/app/imageupload/page.js
Improvements so images can be tagged directly in the uploader instead of later in Prisma Studio.
=> Add Campus, Difficulty, and Indoors selections to uploader

frontend/app/play/_components/DebugMenu.js, frontend/app/play/_components/GameView.js, frontend/app/play/_components/MapWrapper.js, frontend/app/play/_components/ResultsDialog.js, frontend/app/play/_components/StatsMenu.js, frontend/app/play/page.js
- stats window, similar to debug (score, last distance, etc.)
- preview image on map view, clickable to return home
- hide home screen buttons when viewing map
- better rendering on mobile
=> Dev stats image preview

frontend/app/_utils/getDbIsAdmin.js, frontend/app/admin/upload/page.js
Allow the verification of isAdmin status with a db query on high importance routes
=> verify isAdmin status in db

frontend/app/admin/@modal/(.)photos/[id]/_components/Modal.js, frontend/app/admin/@modal/(.)photos/[id]/page.js, frontend/app/admin/@modal/default.js, frontend/app/admin/@modal/loading.js, frontend/app/admin/_components/PhotoEditBackButton.js, frontend/app/admin/_components/PhotoEditForm.js, frontend/app/admin/_components/PhotoEditMapView.js, frontend/app/admin/_components/PhotoEditWrapper.js, frontend/app/admin/layout.js, frontend/app/admin/loading.js, frontend/app/admin/map/_components/MapView.js, frontend/app/admin/map/page.js, frontend/app/admin/page.js, frontend/app/admin/photos/[id]/page.js, frontend/app/admin/photos/_components/Table.js, frontend/app/admin/photos/page.js, frontend/app/admin/upload/page.js, frontend/package-lock.json, frontend/package.json
Added a sortable and filterable table view to the admin page to make finding specific photos easier.
Also added an editor view allowing admins to change the location and metadata (title, description, difficulty, etc) on a photo.
=> Location edit feature and admin table view

frontend/app/_components/HomeWrapper.js, frontend/app/page.js, frontend/app/play/_components/EndDialog.js, frontend/app/play/_components/GameView.js, frontend/app/play/_components/MapWrapper.js, frontend/app/play/_components/ResultsDialog.js, frontend/app/play/page.js
The home page now shows a continue game button if the user is in the middle of a game.
I also added a "Go Home" button to the end screen.
These tweaks make the UX flow a lot better.
=> Home page tweaks and add go home button to end screen

frontend/app/play/page.js, frontend/app/profile/page.js
- Stores user high score in DB if it is set
- Displays high score message
=> User High Score

frontend/app/play/page.js
for leaderboard stats, use user ip address if not logged in
=> add ip based users

frontend/app/_components/HomeWrapper.js, frontend/app/leaderboard/_components/LeaderBoardWrapper.js, frontend/app/leaderboard/page.js, frontend/app/lobby/_components/Timer.js, frontend/app/lobby/page.js, frontend/app/play/_components/EndDialog.js, frontend/app/play/_components/GameView.js, frontend/app/play/_components/MapWrapper.js, frontend/app/play/_components/ResultsDialog.js, frontend/app/play/page.js, frontend/package-lock.json, frontend/package.json, frontend/prisma/migrations/20241202000917_add_lobbies/migration.sql, frontend/prisma/migrations/20241202001056_code_is_int/migration.sql, frontend/prisma/schema.prisma
Add timed multiplayer lobbies where a user can create a lobby and share a qr code so that everyone gets the same 5 images. After the time is up, a leaderboard for the lobby is automatically shown to the user who set the lobby up.
Screenshots:
=> Add multiplayer lobbies

frontend/app/_components/Leaflet.js, frontend/app/_components/LeafletMarker.js, frontend/app/admin/_components/PhotoEditMapView.js, frontend/app/admin/map/_components/MapView.js, frontend/app/play/_components/EndDialog.js, frontend/app/play/_components/MapWrapper.js, frontend/app/play/_components/ResultsDialog.js
All the maps now zoom automatically to fit all the markers (on mobile and desktop!)
=> fix zoom & better horizontal progress

frontend/app/login/continue/route.js, frontend/app/login/page.js, frontend/app/play/_components/GameView.js, frontend/app/play/_components/MapWrapper.js, frontend/app/play/_components/ResultsLeaderboard.js, frontend/app/play/page.js
- Include leaderboard once game completes
- Prompt users to log in to save scores
- Added searchParams to login page recording the gameState Id
- Differ messages base on Logged In status, leaderboard score status
=> Leaderboard on Results Screen

frontend/app/login/_components/LoadScript.js, frontend/app/login/page.js
=> fix google login button disappearing

web/app/_components/HomeWrapper.js, web/app/join/page.js, web/app/lobby/_components/LobbyLeaderboard.js, web/app/lobby/page.js, web/app/play/_components/EndDialog.js, web/app/play/_components/GameView.js, web/app/play/_components/MapWrapper.js, web/app/play/page.js
- Live updating LobbyLeaderboard component
- /join route
- Join with 6 digit code directly
- New homescreen icon
=> poll for live multiplayer leaderboard + join by code

web/app/admin/userstats/page.js, web/app/api_upload/route.ts, web/app/play/page.js
- Fixes bug where user high scores are not updated
- Add admin page to view analytics
- Add API uploader for mobile image uploads
=> Merge dev into main (RELEASE 0.8.1)

mobile/app/(tabs)/take-photo.js, web/app/_components/HomeWrapper.js, web/app/layout.js, web/app/login/page.js, web/app/privacy/page.js, web/app/public_upload/_components/UploadForm.js, web/app/public_upload/page.js, web/app/terms/page.js, web/package-lock.json, web/package.json, web/tailwind.config.js
- Polish public upload form
- Add Privacy Policy and Terms of Service
- Google site verification
- Progress on mobile dev
=> Merge dev into main (RELEASE 0.8.2)
